## Educação em Goiânia e Goiás

Utilizando as bibliotecas Pandas e Numpy, realizamos uma análise dos principais índices e informações extraídas da base de microdados do Censo Escolar 2022, divulgados pelo Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (Inep), do Ministério da Educação (MEC) de Goiânia e demais cidades de Goiás. Nessa análise, exploramos dados relacionados à educação, como o número de escolas, a dependência da escola, a localização, o tipo de ensino e outros aspectos relevantes.

In [ ]:
import pandas as pd
import numpy as np

### Escolas

Este código em Python realiza a leitura de um arquivo CSV contendo dados sobre educação em Goiânia, aplica transformações e formatações nos dados para prepará-los para análises subsequentes.

In [ ]:
# Carrega os dados do arquivo CSV
dados = pd.read_csv('I:\TRABALHO, MBA, ETC\Virtu\Radar\Clientes\Península\Dados\Inep\Educação básica\microdados_censo_escolar_2022\Microdados do Censo Escolar da Educação Básica 2022\dados\microdados_ed_basica_2022.csv', sep=';', encoding='latin-1', low_memory=False)

# Filtra os dados para manter apenas escolas em funcionamento
dados = dados[dados['TP_SITUACAO_FUNCIONAMENTO'] == 1]

# Seleciona as colunas relevantes para análise
dados = dados[['NO_REGIAO', 'NO_UF', 'SG_UF', 'NO_MUNICIPIO', 'NO_MICRORREGIAO', 'NO_ENTIDADE', 'TP_DEPENDENCIA', 'NO_BAIRRO', 'TP_LOCALIZACAO', 'NU_DDD', 'NU_TELEFONE',
               'IN_INF', 'IN_FUND', 'IN_MED']]

# Mapeia o código de dependência da escola para uma descrição legível
legenda = {
    1: 'Federal',
    2: 'Estadual',
    3: 'Municipal',
    4: 'Privada'
}
dados['TP_DEPENDENCIA'] = dados['TP_DEPENDENCIA'].map(legenda)

# Mapeia o código de localização da escola para uma descrição legível
legenda_localizacao = {
    1: 'Urbana',
    2: 'Rural'
}
dados['TP_LOCALIZACAO'] = dados['TP_LOCALIZACAO'].map(legenda_localizacao)

# Formata o número de telefone como "(DDD) Número"
def formatar_telefone(row):
    return f"({row['NU_DDD']}) {row['NU_TELEFONE']}"
dados['TELEFONE'] = dados.apply(formatar_telefone, axis=1)

# Remove as colunas NU_DDD e NU_TELEFONE
dados = dados.drop(columns=['NU_DDD', 'NU_TELEFONE'])

# Renomeia as colunas
dados.columns = ['Região', 'Estado', 'Sigla UF', 'Município', 'Microrregião', 'Nome da escola', 'Dependência da escola', 'Bairro', 'Tipo da localização',
                 'Educação Infantil', 'Ensino Fundamental', 'Ensino Médio', 'Telefone']

# Substitui valores infinitos por NaN
dados.replace([np.inf, -np.inf], np.nan, inplace=True)

# Converte as colunas numéricas para o tipo inteiro
dados['Educação Infantil'] = dados['Educação Infantil'].astype(float).fillna(0).astype(int)
dados['Ensino Fundamental'] = dados['Ensino Fundamental'].astype(float).fillna(0).astype(int)
dados['Ensino Médio'] = dados['Ensino Médio'].astype(float).fillna(0).astype(int)

# Exibe as primeiras linhas dos dados
dados.head()

,Região,Estado,Sigla UF,Município,Microrregião,Nome da escola,Dependência da escola,Bairro,Tipo da localização,Educação Infantil,Ensino Fundamental,Ensino Médio,Telefone
0,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,EIEEF HAP BITT TUPARI,Estadual,RURAL,Rural,0,1,0,(69) 36413839
1,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,CEEJA LUIZ VAZ DE CAMOES,Estadual,CIDADE ALTA,Urbana,0,0,0,(69) 36412656
2,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,EMMEF 7 DE SETEMBRO,Municipal,NaN,Rural,0,1,0,(69) 36413630
3,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,EMEIEF ANA NERY,Municipal,NaN,Urbana,1,1,0,(69) 36413630
4,Norte,Rondônia,RO,Alta Floresta D'Oeste,Cacoal,EMEIEF BOA ESPERANCA,Municipal,LINHA P.50,Rural,1,1,0,(69) 9.8431E8

Neste trecho de código, serão selecionados os dados referentes ao estado de Goiás, excluindo os registros do município de Goiânia. Em seguida, serão removidas as duplicatas e os registros que possuem valores ausentes na coluna 'Bairro'.

In [ ]:
# Seleciona os dados do estado de Goiás, excluindo o município de Goiânia
goias = dados[(dados['Estado'] == 'Goiás') & (dados['Município'] != 'Goiânia')]

# Remove as duplicatas nos dados selecionados
goias = goias.drop_duplicates()

# Remove os registros com valores ausentes na coluna 'Bairro'
goias = goias.dropna(subset=['Bairro'])

,Região,Estado,Sigla UF,Município,Microrregião,Nome da escola,Dependência da escola,Bairro,Tipo da localização,Educação Infantil,Ensino Fundamental,Ensino Médio,Telefone
217691,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,ESCOLA MUNICIPAL VITAL LUIZ DA COSTA,Municipal,SETOR QUINTA DOS SONHOS,Rural,1,1,0,(62) 99149576
217692,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,ESCOLA MUNICIPAL NOSSA SENHORA DO PERPETUO SOC...,Municipal,VILA NOSSA SENHORA DO PERPETUO SOCORRO,Urbana,1,1,0,(62) 9.9308E8
217693,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,COLEGIO ESTADUAL MANOEL LIBANIO DA SILVA,Estadual,VILA GOIANY,Urbana,0,1,1,(62) 35031139
217694,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,ESCOLA MUNICIPAL PAULINO INACIO ROSA,Municipal,SETOR PARQUE IZABEL,Urbana,0,1,0,(62) 35031790
217695,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,CENTRO MUNICIPAL DE EDUCACAO INFANTIL JOSE PED...,Municipal,CENTRO,Urbana,1,0,0,(62) 35031105
...,...,...,...,...,...,...,...,...,...,...,...,...,...
223151,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,COLEGIO ESTADUAL DOM PEDRO II,Estadual,POV ASSUNCAO DE GOIAS,Rural,0,1,1,(62) 9.9802E8
223152,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,COLEGIO ESTADUAL JOSE DE ANCHIETA,Estadual,CENTRO,Urbana,0,1,1,(62) 33200420
223154,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,ESCOLA MUNICIPAL PROFESSOR JOSE LOPES,Municipal,CENTRO,Urbana,1,1,0,(62) 33200196
223155,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,ESCOLA MUNICIPAL GEDOR DE ASSUNCAO,Municipal,ASSUNCAO DE GOIAS,Rural,1,1,0,(62) 34041095
223156,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,CRECHE MUNICIPAL BENEDITO PEREIRA DE SIQUEIRA,Municipal,CENTRO,Urbana,1,0,0,(62) 33200196

Neste trecho de código, serão selecionados os dados referentes ao estado de Goiás, excluindo os registros do município de Goiânia. Em seguida, serão removidas as duplicatas e os registros que possuem valores ausentes na coluna 'Bairro'.

In [ ]:
# Seleciona os dados do estado de Goiás, excluindo o município de Goiânia
goias = dados[(dados['Estado'] == 'Goiás') & (dados['Município'] != 'Goiânia')]

# Remove as duplicatas nos dados selecionados
goias = goias.drop_duplicates()

# Remove os registros com valores ausentes na coluna 'Bairro'
goias = goias.dropna(subset=['Bairro'])

Neste trecho de código, os dados referentes ao estado de Goiás (excluindo o município de Goiânia) são preparados para exportação em um arquivo CSV, exibidos na tela e também armazenados em um objeto chamado goias_geral.

In [ ]:
# Remove as colunas 'Educação Infantil', 'Ensino Fundamental' e 'Ensino Médio' do dataframe
goias_geral = goias.drop(columns=['Educação Infantil', 'Ensino Fundamental', 'Ensino Médio'])

# Exporta os dados para um arquivo CSV
goias_geral.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Escolas_goias_geral.csv', index=False)

# Imprime o número total de escolas funcionando nos municípios do estado de Goiás (exceto Goiânia)
print(f"O número total de escolas funcionando nos municípios no estado de Goiás (exceto Goiânia) é de {len(goias_geral['Nome da escola'])}.")

# Exibe os dados do dataframe 'goias_geral'
goias_geral

O número total de escolas funcionando nos municípios no estado de Goiânia (exceto Goiás) é de 3816.

,Região,Estado,Sigla UF,Município,Microrregião,Nome da escola,Dependência da escola,Bairro,Tipo da localização,Telefone
217691,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,ESCOLA MUNICIPAL VITAL LUIZ DA COSTA,Municipal,SETOR QUINTA DOS SONHOS,Rural,(62) 99149576
217692,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,ESCOLA MUNICIPAL NOSSA SENHORA DO PERPETUO SOC...,Municipal,VILA NOSSA SENHORA DO PERPETUO SOCORRO,Urbana,(62) 9.9308E8
217693,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,COLEGIO ESTADUAL MANOEL LIBANIO DA SILVA,Estadual,VILA GOIANY,Urbana,(62) 35031139
217694,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,ESCOLA MUNICIPAL PAULINO INACIO ROSA,Municipal,SETOR PARQUE IZABEL,Urbana,(62) 35031790
217695,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,CENTRO MUNICIPAL DE EDUCACAO INFANTIL JOSE PED...,Municipal,CENTRO,Urbana,(62) 35031105
...,...,...,...,...,...,...,...,...,...,...
223151,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,COLEGIO ESTADUAL DOM PEDRO II,Estadual,POV ASSUNCAO DE GOIAS,Rural,(62) 9.9802E8
223152,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,COLEGIO ESTADUAL JOSE DE ANCHIETA,Estadual,CENTRO,Urbana,(62) 33200420
223154,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,ESCOLA MUNICIPAL PROFESSOR JOSE LOPES,Municipal,CENTRO,Urbana,(62) 33200196
223155,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,ESCOLA MUNICIPAL GEDOR DE ASSUNCAO,Municipal,ASSUNCAO DE GOIAS,Rural,(62) 34041095
223156,Centro-Oeste,Goiás,GO,Vila Propício,Entorno de Brasília,CRECHE MUNICIPAL BENEDITO PEREIRA DE SIQUEIRA,Municipal,CENTRO,Urbana,(62) 33200196

Neste trecho de código, é criada uma tabela dinâmica chamada escolas_dependencia que contém o total de escolas por tipo de dependência em cada município de Goiás. Em seguida, é exibido o total de escolas por tipo de dependência nos municípios de Goiás e os resultados são exportados para um arquivo CSV. Por fim, os dados da tabela escolas_dependencia são exibidos na tela.

In [ ]:
# Cria a tabela dinâmica com o total de escolas por tipo de dependência em cada município de Goiás
escolas_dependencia = goias.pivot_table(index='Município', columns='Dependência da escola', aggfunc='size', fill_value=0)

# Imprime o total de escolas por tipo de dependência nos municípios de Goiás
print(f"O total de escolas por tipo de dependência nos {len(escolas_dependencia['Município'])} municípios de Goiás é de: Estadual: {escolas_dependencia['Estadual'].sum()}; Federal: {escolas_dependencia['Federal'].sum()}; Municipal: {escolas_dependencia['Municipal'].sum()} e Privada: {escolas_dependencia['Privada'].sum()}.")

# Exporta os dados da tabela 'escolas_dependencia' para um arquivo CSV
escolas_dependencia.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Escolas_goias_por_dependencia.csv', index=False)

# Exibe os dados da tabela 'escolas_dependencia'
escolas_dependencia

O total de escolas por tipo de dependência nos 245 municíos de Goiás é de: Estadual: 860; 860; Federal 23; Municipal 2117 e Privada 816.

                 Município  Estadual  Federal  Municipal  Privada
0          Abadia de Goiás         1        0          7        1
1                Abadiânia         2        0          7        4
2                  Acreúna         3        0          9        3
3                Adelândia         1        0          2        0
4                 Alexânia         4        0         19        4
..                     ...       ...      ...        ...      ...
240               Vila Boa         1        0          6        0
241          Vila Propício         2        0          3        0
242     Água Fria de Goiás         2        0          3        0
243             Água Limpa         1        0          2        0
244  Águas Lindas de Goiás        17        1         47       49

[245 rows x 5 columns]

Neste trecho de código, são realizadas análises sobre o total de escolas por tipo de localização nos municípios de Goiás. Os resultados são exibidos na tela e também exportados para um arquivo CSV.

In [ ]:
# Agrupa os dados por município e tipo de localização, calculando o total de escolas
escolas_localizacao = goias.groupby(['Município', 'Tipo da localização']).size().reset_index(name='Total de escolas')

# Calcula o total de escolas por tipo de localização
total_escolas_por_localizacao = escolas_localizacao.groupby('Tipo da localização')['Total de escolas'].sum()

# Exibe o total de escolas por tipo de localização
for localizacao, total in total_escolas_por_localizacao.items():
    print(f"O total de escolas do tipo {localizacao} é de {total}.")

# Exporta os dados da tabela 'escolas_localizacao' para um arquivo CSV
escolas_localizacao.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Escolas_goias_por_localizacao.csv', index=False)

# Exibe os dados da tabela 'escolas_localizacao'
escolas_localizacao

O total de escolas do tipo Rural é de 401.
O total de escolas do tipo Urbana é de 3415.

                 Município Tipo da localização  Total de escolas
0          Abadia de Goiás               Rural                 1
1          Abadia de Goiás              Urbana                 8
2                Abadiânia               Rural                 3
3                Abadiânia              Urbana                10
4                  Acreúna              Urbana                15
..                     ...                 ...               ...
366     Água Fria de Goiás               Rural                 2
367     Água Fria de Goiás              Urbana                 3
368             Água Limpa              Urbana                 3
369  Águas Lindas de Goiás               Rural                 4
370  Águas Lindas de Goiás              Urbana               110

[371 rows x 3 columns]

Neste trecho de código, é realizado o cálculo do total de escolas por bairro nos municípios de Goiás. Os resultados são exibidos na tela e também exportados para um arquivo CSV.

In [ ]:
# Agrupa os dados por município e bairro, calculando o total de escolas
total_por_bairro = goias.groupby(['Município', 'Bairro']).size().reset_index(name='Total de escolas')

# Exibe o total de escolas por tipo de dependência nos municípios de Goiás
print(f"O total de escolas por tipo de dependência nos {len(total_por_bairro['Município'])} municípios de Goiás é de: Estadual: {total_por_bairro['Estadual'].sum()}; Federal: {escolas_dependencia['Federal'].sum()}; Municipal: {escolas_dependencia['Municipal'].sum()} e Privada: {escolas_dependencia['Privada'].sum()}.")

# Exporta os dados da tabela 'total_por_bairro' para um arquivo CSV
total_por_bairro.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Escolas_goias_por_bairro.csv', index=False)

# Exibe os dados da tabela 'total_por_bairro'
total_por_bairro

Ao todo, 3816 escolas em Goiás estão divididas em 1408 bairros em 245 municípios.

                  Município                      Bairro  Total de escolas
0           Abadia de Goiás                      CENTRO                 1
1           Abadia de Goiás              JARDIM FLORITA                 1
2           Abadia de Goiás  RESIDENCIAL JARDIM FLORITA                 1
3           Abadia de Goiás       RESIDENCIAL PAINEIRAS                 1
4           Abadia de Goiás         SETOR PARQUE IZABEL                 1
...                     ...                         ...               ...
2045  Águas Lindas de Goiás                    SETOR 08                 1
2046  Águas Lindas de Goiás                    SETOR 11                 1
2047  Águas Lindas de Goiás                    SETOR 14                 1
2048  Águas Lindas de Goiás                     SETOR 2                 1
2049  Águas Lindas de Goiás               SETOR COIMBRA                 1

[2050 rows x 3 columns]

Neste trecho de código, é realizado o cálculo do total de escolas por tipo de ensino nos municípios de Goiás. Os resultados são exibidos na tela, exportados para um arquivo CSV e armazenados no dataframe escolas_por_ensino.

In [ ]:
# Agrupa os dados por município, somando o total de escolas por tipo de ensino
escolas_por_ensino = goias.groupby('Município')['Educação Infantil', 'Ensino Fundamental', 'Ensino Médio'].sum().reset_index()

# Exibe o total de escolas por tipo de ensino nos municípios de Goiás
print(f"O total de escolas por tipo de ensino nos {len(escolas_por_ensino['Município'])} municípios de Goiás é de: {escolas_por_ensino['Educação Infantil'].sum()} no Ensino Infantil; {escolas_por_ensino['Ensino Fundamental'].sum()} no Ensino Fundamental e {escolas_por_ensino['Ensino Médio'].sum()} no Ensino Médio.")

# Exporta os dados da tabela 'escolas_por_ensino' para um arquivo CSV
escolas_por_ensino.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Escolas_goias_por_ensino.csv', index=False)

# Exibe os dados da tabela 'escolas_por_ensino'
escolas_por_ensino

O total de escolas por tipo de tipo de ensino nos 245 municíos de Goiás é de: 2141 no Ensino Infantil; 2732 no Ensino Fundamental e 897 no Ensino Médio.

C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_35060\2749087335.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  escolas_por_ensino = goias.groupby('Município')['Educação Infantil', 'Ensino Fundamental', 'Ensino Médio'].sum().reset_index()

,Município,Educação Infantil,Ensino Fundamental,Ensino Médio
0,Abadia de Goiás,5,7,1
1,Abadiânia,6,11,3
2,Acreúna,8,10,5
3,Adelândia,1,2,1
4,Alexânia,16,24,4
...,...,...,...,...
240,Vila Boa,4,5,1
241,Vila Propício,3,4,2
242,Água Fria de Goiás,2,5,2
243,Água Limpa,1,2,1
244,Águas Lindas de Goiás,76,89,32

### MATRÍCULAS

Utilizando as bibliotecas Pandas e Numpy, faremos uma análise dos dados da educação básica em Goiás, utilizando os microdados do Censo Escolar 2022 fornecidos pelo Inep/MEC. Serão explorados aspectos como matrículas por nível de ensino, dependência e localização das escolas.

In [ ]:
# Leitura do arquivo CSV com os dados do Censo Escolar 2022
dados = pd.read_csv('I:\TRABALHO, MBA, ETC\Virtu\Radar\Clientes\Península\Dados\Inep\Educação básica\microdados_censo_escolar_2022\Microdados do Censo Escolar da Educação Básica 2022\dados\microdados_ed_basica_2022.csv', sep=';', encoding='latin-1', low_memory=False)

# Filtragem dos dados para escolas em funcionamento
dados = dados[dados['TP_SITUACAO_FUNCIONAMENTO'] == 1]

# Filtragem dos dados para o estado de Goiás, excluindo Goiânia
dados = dados[dados['NO_UF'] == 'Goiás']
dados = dados[dados['NO_MUNICIPIO'] != 'Goiânia']

# Mapeamento dos códigos de dependência e localização para suas respectivas descrições
legenda = {
    1: 'Federal',
    2: 'Estadual',
    3: 'Municipal',
    4: 'Privada'
}
dados['TP_DEPENDENCIA'] = dados['TP_DEPENDENCIA'].map(legenda)

legenda_localizacao = {
    1: 'Urbana',
    2: 'Rural'
}
dados['TP_LOCALIZACAO'] = dados['TP_LOCALIZACAO'].map(legenda_localizacao)

# Seleção das colunas relevantes para análise de matrículas
dados_matriculas = dados[['NO_REGIAO', 'NO_UF', 'SG_UF', 'NO_MUNICIPIO', 'NO_MICRORREGIAO', 'NO_BAIRRO', 'NO_ENTIDADE', 'TP_DEPENDENCIA', 'TP_LOCALIZACAO', 'QT_MAT_BAS', 'QT_MAT_INF',
               'QT_MAT_FUND', 'QT_MAT_MED', 'QT_MAT_PROF_TEC', 'QT_MAT_EJA', 'QT_MAT_ESP']]

# Renomeação das colunas para melhor legibilidade
dados_matriculas.columns = ['Região', 'Estado', 'Sigla UF', 'Município', 'Microrregião', 'Bairro', 'Nome da escola', 'Tipo de dependência', 'Tipo de localização', 'Matrículas Educação Básica',
                          'Matrículas Educação Infantil', 'Matrículas Ensino Fundamental', 'Matrículas Ensino Médio', 'Matrículas Educação Profissional Técnico',
                          'Matrículas Educação de Jovens e Adultos', 'Matrículas Educação Especial']

# Tratamento de valores infinitos e ausentes
dados_matriculas.replace([np.inf, -np.inf], np.nan, inplace=True)

# Conversão dos tipos de dados das colunas de matrículas para inteiros
dados_matriculas['Matrículas Educação Básica'] = dados_matriculas['Matrículas Educação Básica'].astype(float).fillna(0).astype(int)
dados_matriculas['Matrículas Educação Infantil'] = dados_matriculas['Matrículas Educação Infantil'].astype(float).fillna(0).astype(int)
dados_matriculas['Matrículas Ensino Fundamental'] = dados_matriculas['Matrículas Ensino Fundamental'].astype(float).fillna(0).astype(int)
dados_matriculas['Matrículas Ensino Médio'] = dados_matriculas['Matrículas Ensino Médio'].astype(float).fillna(0).astype(int)
dados_matriculas['Matrículas Educação Profissional Técnico'] = dados_matriculas['Matrículas Educação Profissional Técnico'].astype(float).fillna(0).astype(int)
dados_matriculas['Matrículas Educação de Jovens e Adultos'] = dados_matriculas['Matrículas Educação de Jovens e Adultos'].astype(float).fillna(0).astype(int)
dados_matriculas['Matrículas Educação Especial'] = dados_matriculas['Matrículas Educação Especial'].astype(float).fillna(0).astype(int)

C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\2864592564.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_matriculas.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\2864592564.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_matriculas['Matrículas Educação Básica'] = dados_matriculas['Matrículas Educação Básica'].astype(float).fillna(0).astype(int)
C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\2864592564.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_matriculas['Matrículas Educação Infantil'] = dados_matriculas['Matrículas Educação Infantil'].astype(float).fillna(0).astype(int)
C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\2864592564.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_matriculas['Matrículas Ensino Fundamental'] = dados_matriculas['Matrículas Ensino Fundamental'].astype(float).fillna(0).astype(int)
C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\2864592564.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_matriculas['Matrículas Ensino_Médio'] = dados_matriculas['Matrículas Ensino_Médio'].astype(float).fillna(0).astype(int)
C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\2864592564.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_matriculas['Matrículas Educação Profissional Técnico'] = dados_matriculas['Matrículas Educação Profissional Técnico'].astype(float).fillna(0).astype(int)
C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\2864592564.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_matriculas['Matrículas Educação de Jovens e Adultos'] = dados_matriculas['Matrículas Educação de Jovens e Adultos'].astype(float).fillna(0).astype(int)
C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\2864592564.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_matriculas['Matrículas Educação Especial'] = dados_matriculas['Matrículas Educação Especial'].astype(float).fillna(0).astype(int)

In [ ]:
# Exibe informações sobre o dataframe 'dados_matriculas'
dados_matriculas.info()

# Exibe as primeiras 2 linhas do dataframe 'dados_matriculas'
dados_matriculas.head(2)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3923 entries, 217691 to 223157
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Região                                    3923 non-null   object
 1   Estado                                    3923 non-null   object
 2   Sigla UF                                  3923 non-null   object
 3   Município                                 3923 non-null   object
 4   Microrregião                              3923 non-null   object
 5   Bairro                                    3816 non-null   object
 6   Nome da escola                            3923 non-null   object
 7   Tipo de dependência                       3923 non-null   object
 8   Tipo de localização                       3923 non-null   object
 9   Matrículas Educação Básica                3923 non-null   int32
 10  Matrículas Educação Infantil              3923 non-null   int32
 11  Matrículas Ensino Fundamental             3923 non-null   int32
 12  Matrículas Ensino_Médio                   3923 non-null   int32
 13  Matrículas Educação Profissional Técnico  3923 non-null   int32
 14  Matrículas Educação de Jovens e Adultos   3923 non-null   int32
 15  Matrículas Educação Especial              3923 non-null   int32
dtypes: int32(7), object(9)
memory usage: 413.8+ KB

,Região,Estado,Sigla UF,Município,Microrregião,Bairro,Nome da escola,Tipo de dependência,Tipo de localização,Matrículas Educação Básica,Matrículas Educação Infantil,Matrículas Ensino Fundamental,Matrículas Ensino_Médio,Matrículas Educação Profissional Técnico,Matrículas Educação de Jovens e Adultos,Matrículas Educação Especial
217691,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,SETOR QUINTA DOS SONHOS,ESCOLA MUNICIPAL VITAL LUIZ DA COSTA,Municipal,Rural,689,153,536,0,0,0,14
217692,Centro-Oeste,Goiás,GO,Abadia de Goiás,Goiânia,VILA NOSSA SENHORA DO PERPETUO SOCORRO,ESCOLA MUNICIPAL NOSSA SENHORA DO PERPETUO SOC...,Municipal,Urbana,189,33,156,0,0,0,1

Utilizando as bibliotecas Pandas e Numpy, realizamos uma análise das matrículas na educação básica em Goiás (exceto Goiânia), com base nos microdados do Censo Escolar 2022. Foram analisadas as matrículas por nível de ensino, incluindo Educação Infantil, Ensino Fundamental, Ensino Médio, Educação Profissional Técnico, Educação de Jovens e Adultos e Educação Especial.

In [ ]:
# GOIÁS

# Agrupa os dados por município e realiza a soma das matrículas por tipo de ensino
total_matriculas = dados_matriculas.groupby('Município').sum()[['Matrículas Educação Básica', 'Matrículas Educação Infantil', 'Matrículas Ensino Fundamental',
                                                                'Matrículas Ensino Médio', 'Matrículas Educação Profissional Técnico',
                                                                'Matrículas Educação de Jovens e Adultos', 'Matrículas Educação Especial']]

# Reseta o índice do dataframe 'total_matriculas'
total_matriculas = total_matriculas.reset_index()

# Exporta os dados do dataframe 'total_matriculas' para um arquivo CSV
total_matriculas.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goias - Total de matrículas.csv', index=False)

# Exibe as informações sobre as matrículas em Goiás
print(f"As matrículas de Goiás (exceto Goiânia) são: {total_matriculas['Matrículas Educação Básica'].sum()} no total da Educação Básica, divididos em {total_matriculas['Matrículas Educação Infantil'].sum()} na Educação Infantil; {total_matriculas['Matrículas Ensino Fundamental'].sum()} no Ensino Fundamental; {total_matriculas['Matrículas Ensino Médio'].sum()} no Ensino Médio; {total_matriculas['Matrículas Educação Profissional Técnico'].sum()} na Educação Profissional Técnico; {total_matriculas['Matrículas Educação de Jovens e Adultos'].sum()} na Educação de Jovens e Adultos; e {total_matriculas['Matrículas Educação Especial'].sum()} na Educação Especial.")

# Exibe o dataframe 'total_matriculas'
total_matriculas

As matrículas de Goiás (exceto Goiânia) são: 1172147 no total da Educação Básica, divididos em 208114 na Educação Infantil; 709015 no Ensino Fundamental; 200368 no Ensino Médio; 24950 na Educação Profissional Técnico; 38143 na Educação de Jovens e Adultos; e 44760 na Educação Especial.

C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\2748726076.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  total_matriculas = dados_matriculas.groupby('Município').sum()[['Matrículas Educação Básica', 'Matrículas Educação Infantil', 'Matrículas Ensino Fundamental',

,Município,Matrículas Educação Básica,Matrículas Educação Infantil,Matrículas Ensino Fundamental,Matrículas Ensino_Médio,Matrículas Educação Profissional Técnico,Matrículas Educação de Jovens e Adultos,Matrículas Educação Especial
0,Abadia de Goiás,3921,665,2653,554,0,49,101
1,Abadiânia,3561,418,2199,883,0,61,60
2,Acreúna,4442,961,2576,736,27,169,152
3,Adelândia,403,82,248,73,0,0,7
4,Alexânia,6151,1139,3786,1149,0,77,177
...,...,...,...,...,...,...,...,...
240,Vila Boa,1221,225,733,222,0,41,32
241,Vila Propício,1290,256,757,277,0,0,49
242,Água Fria de Goiás,1099,131,735,187,0,46,24
243,Água Limpa,384,113,213,53,0,5,30
244,Águas Lindas de Goiás,50367,7239,32751,8484,938,1301,1344

Mesmo procedimento, agora somente com a capital Goiânia.

In [ ]:
# Agrupa os dados por município e realiza a soma das matrículas por tipo de ensino
total_matriculas = dados_matriculas.groupby('Município').sum()[['Matrículas Educação Básica', 'Matrículas Educação Infantil', 'Matrículas Ensino Fundamental',
                                                                'Matrículas Ensino Médio', 'Matrículas Educação Profissional Técnico',
                                                                'Matrículas Educação de Jovens e Adultos', 'Matrículas Educação Especial']]

# Transpõe os dados para uma visualização mais clara
total_matriculas_transpose = total_matriculas.transpose()

# Reseta o índice do dataframe 'total_matriculas_transpose'
total_matriculas_transpose.reset_index(inplace=True)

# Renomeia as colunas para uma melhor descrição
total_matriculas_transpose.rename(columns={'index': 'Matrículas'}, inplace=True)
total_matriculas_transpose.rename(columns={'Goiânia': 'Total'}, inplace=True)

# Exibe o total de matrículas em Goiânia por tipo de ensino
for index, row in total_matriculas_transpose.iterrows():
    print(f"O total de {row['Matrículas']} em Goiânia é {row['Total']}.")

# Exporta os dados do dataframe 'total_matriculas_transpose' para um arquivo CSV
total_matriculas_transpose.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Total de matrículas.csv', index=False)

# Exibe o dataframe 'total_matriculas_transpose'
total_matriculas_transpose

Realizamos uma análise das matrículas na educação básica em Goiás (exceto Goiânia) com base nos microdados do Censo Escolar 2022. Os resultados foram agrupados por município e tipo de dependência da escola, apresentando o total de matrículas na Educação Básica. Também foram exibidos os totais de matrículas em Goiânia por tipo de dependência.

In [ ]:
# Agrupa os dados por município e tipo de dependência, somando as matrículas na Educação Básica
mat_dependencia = dados_matriculas.groupby(['Município', 'Tipo de dependência'])['Matrículas Educação Básica'].sum().reset_index()

# Agrupa os dados por tipo de dependência, somando as matrículas na Educação Básica
mat_dependencia_print = dados_matriculas.groupby(['Tipo de dependência'])['Matrículas Educação Básica'].sum().reset_index()

# Exibe o total de matrículas em Goiânia por tipo de dependência
for index, row in mat_dependencia_print.iterrows():
    print(f"O total de matrículas em Goiânia é de: {row['Tipo de dependência']} - {row['Matrículas Educação Básica']} matrículas.")

# Exporta os dados do dataframe 'mat_dependencia' para um arquivo CSV
mat_dependencia.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goiás - Total de matrículas por dependencia.csv', index=False)

# Exibe o dataframe 'mat_dependencia'
mat_dependencia

O total de matrítulas em Goiânia é de: Estadual - 414604 matrículas.
O total de matrítulas em Goiânia é de: Federal - 7711 matrículas.
O total de matrítulas em Goiânia é de: Municipal - 582561 matrículas.
O total de matrítulas em Goiânia é de: Privada - 167271 matrículas.

                 Município Tipo de dependência  Matrículas Educação Básica
0          Abadia de Goiás            Estadual                        1079
1          Abadia de Goiás           Municipal                        2734
2          Abadia de Goiás             Privada                         108
3                Abadiânia            Estadual                        1320
4                Abadiânia           Municipal                        1195
..                     ...                 ...                         ...
625             Água Limpa           Municipal                         244
626  Águas Lindas de Goiás            Estadual                       20183
627  Águas Lindas de Goiás             Federal                         460
628  Águas Lindas de Goiás           Municipal                       20964
629  Águas Lindas de Goiás             Privada                        8760

[630 rows x 3 columns]

O mesmo procedimento, agora para Goiânia:

In [ ]:
# GOIÂNIA

# Agrupa os dados por tipo de dependência e realiza a soma das matrículas em cada categoria
mat_dependencia = dados_matriculas.groupby(['Tipo de dependência'])['Matrículas Educação Básica', 'Matrículas Educação Infantil', 'Matrículas Ensino Fundamental',
                                                                 'Matrículas Ensino Médio', 'Matrículas Educação Profissional Técnico',
                                                                 'Matrículas Educação de Jovens e Adultos', 'Matrículas Educação Especial'].sum().reset_index()

# Transpõe os dados para uma visualização mais clara
mat_dependencia_transpose = mat_dependencia.transpose()

# Define as colunas do dataframe como a primeira linha e renomeia as colunas
mat_dependencia_transpose.columns = mat_dependencia_transpose.iloc[0]
mat_dependencia_transpose.reset_index(inplace=True)
mat_dependencia_transpose.rename(columns={'index': 'Matrículas'}, inplace=True)

# Remove a primeira linha do dataframe
mat_dependencia_transpose = mat_dependencia_transpose.drop(0).reset_index(drop=True)

# Exporta os dados do dataframe 'mat_dependencia_transpose' para um arquivo CSV
mat_dependencia_transpose.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Total de matrículas por dependencia.csv', index=False)

# Exibe o total de matrículas por tipo de dependência
for index, row in mat_dependencia_transpose.iterrows():
    print(f"O total de {row['Matrículas']} na rede Estadual é {row['Estadual']}, na Municipal é {row['Municipal']}, na Federal é {row['Federal']} e na Privada é {row['Privada']}.")

# Exibe o dataframe 'mat_dependencia_transpose'
mat_dependencia_transpose

C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\4093555181.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mat_dependencia = dados_matriculas.groupby(['Tipo de dependência'])['Matrículas Educação Básica', 'Matrículas Educação Infantil', 'Matrículas Ensino Fundamental',

O total de Matrículas Educação Básica na rede Estadual é 414604, na Municipal é 582561, na Federal é 7711 e na Privada é 167271.
O total de Matrículas Educação Infantil na rede Estadual é 0, na Municipal é 167921, na Federal é 0 e na Privada é 40193.
O total de Matrículas Ensino Fundamental na rede Estadual é 209590, na Municipal é 405260, na Federal é 0 e na Privada é 94165.
O total de Matrículas Ensino_Médio na rede Estadual é 177148, na Municipal é 488, na Federal é 5638 e na Privada é 17094.
O total de Matrículas Educação Profissional Técnico na rede Estadual é 4264, na Municipal é 0, na Federal é 7298 e na Privada é 13388.
O total de Matrículas Educação de Jovens e Adultos na rede Estadual é 24595, na Municipal é 8892, na Federal é 904 e na Privada é 3752.
O total de Matrículas Educação Especial na rede Estadual é 19568, na Municipal é 20806, na Federal é 113 e na Privada é 4273.

Tipo de dependência,Matrículas,Estadual,Federal,Municipal,Privada
0,Matrículas Educação Básica,414604,7711,582561,167271
1,Matrículas Educação Infantil,0,0,167921,40193
2,Matrículas Ensino Fundamental,209590,0,405260,94165
3,Matrículas Ensino_Médio,177148,5638,488,17094
4,Matrículas Educação Profissional Técnico,4264,7298,0,13388
5,Matrículas Educação de Jovens e Adultos,24595,904,8892,3752
6,Matrículas Educação Especial,19568,113,20806,4273

Realizamos uma análise das matrículas na educação básica em Goiás (exceto Goiânia) com base nos microdados do Censo Escolar 2022. Os resultados foram agrupados por município e tipo de localização da escola, apresentando o total de matrículas em cada categoria. Também foram exibidos os totais de matrículas em Goiás por tipo de localização.

In [ ]:
# GOIÁS

# Agrupa os dados por município e tipo de localização, somando as matrículas na Educação Básica
mat_localidade = dados_matriculas.groupby(['Município', 'Tipo de localização'])['Matrículas Educação Básica'].sum().reset_index()

# Agrupa os dados por tipo de localização, somando as matrículas na Educação Básica
mat_localidade_print = dados_matriculas.groupby(['Tipo de localização'])['Matrículas Educação Básica'].sum().reset_index()

# Exibe o total de matrículas em Goiás por tipo de localização
for index, row in mat_localidade_print.iterrows():
    print(f"O total de matrículas em Goiás é de: {row['Tipo de localização']} - {row['Matrículas Educação Básica']} matrículas.")

# Exporta os dados do dataframe 'mat_localidade' para um arquivo CSV
mat_localidade.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goias - Total de matrículas por localização.csv', index=False)

# Exibe o dataframe 'mat_localidade'
mat_localidade

O total de matrítulas em Goiás é de: Rural - 46703 matrículas.
O total de matrítulas em Goiás é de: Urbana - 1125444 matrículas.

                 Município Tipo de localização  Matrículas Educação Básica
0          Abadia de Goiás               Rural                         689
1          Abadia de Goiás              Urbana                        3232
2                Abadiânia               Rural                         993
3                Abadiânia              Urbana                        2568
4                  Acreúna              Urbana                        4442
..                     ...                 ...                         ...
376     Água Fria de Goiás               Rural                         224
377     Água Fria de Goiás              Urbana                         875
378             Água Limpa              Urbana                         384
379  Águas Lindas de Goiás               Rural                         497
380  Águas Lindas de Goiás              Urbana                       49870

[381 rows x 3 columns]

O mesmo procedimento, agora para Goiânia:

In [ ]:
# Agrupa os dados por tipo de localização e realiza a soma das matrículas em cada categoria
mat_localidade = dados_matriculas.groupby(['Tipo de localização'])['Matrículas Educação Básica', 'Matrículas Educação Infantil', 'Matrículas Ensino Fundamental',
                                                                 'Matrículas Ensino Médio', 'Matrículas Educação Profissional Técnico',
                                                                 'Matrículas Educação de Jovens e Adultos', 'Matrículas Educação Especial'].sum().reset_index()

# Transpõe os dados para uma visualização mais clara
mat_dependencia_transpose = mat_localidade.transpose()

# Define as colunas do dataframe como a primeira linha e renomeia as colunas
mat_dependencia_transpose.columns = mat_dependencia_transpose.iloc[0]
mat_dependencia_transpose.reset_index(inplace=True)
mat_dependencia_transpose.rename(columns={'index': 'Matrículas'}, inplace=True)

# Remove a primeira linha do dataframe
mat_dependencia_transpose = mat_dependencia_transpose.drop(0).reset_index(drop=True)

# Exporta os dados do dataframe 'mat_dependencia_transpose' para um arquivo CSV
mat_dependencia_transpose.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Total de matrículas por localização.csv', index=False)

# Exibe o total de matrículas por tipo de localização
for index, row in mat_dependencia_transpose.iterrows():
    print(f"O total de {row['Matrículas']} na região Rural é {row['Rural']} e na Urbana é {row['Urbana']}.")

# Exibe o dataframe 'mat_dependencia_transpose'
mat_dependencia_transpose

O total de Matrículas Educação Básica na região Rural é 263 e na Urbana é 266467.
O total de Matrículas Educação Infantil na região Rural é 58 e na Urbana é 49045.
O total de Matrículas Ensino Fundamental na região Rural é 205 e na Urbana é 153592.
O total de Matrículas Ensino_Médio na região Rural é 0 e na Urbana é 48796.
O total de Matrículas Educação Profissional Técnico na região Rural é 0 e na Urbana é 7770.
O total de Matrículas Educação de Jovens e Adultos na região Rural é 0 e na Urbana é 9423.
O total de Matrículas Educação Especial na região Rural é 6 e na Urbana é 7042.

C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_25840\3045620725.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mat_dependencia = dados_matriculas.groupby(['Tipo de localização'])['Matrículas Educação Básica', 'Matrículas Educação Infantil', 'Matrículas Ensino Fundamental',

Tipo de localização                                Matrículas Rural  Urbana
0                                  Matrículas Educação Básica   263  266467
1                                Matrículas Educação Infantil    58   49045
2                               Matrículas Ensino Fundamental   205  153592
3                                     Matrículas Ensino_Médio     0   48796
4                    Matrículas Educação Profissional Técnico     0    7770
5                     Matrículas Educação de Jovens e Adultos     0    9423
6                                Matrículas Educação Especial     6    7042

Realizamos uma análise das matrículas na educação básica em Goiás (exceto Goiânia) com base nos microdados do Censo Escolar 2022. Os resultados foram agrupados por município e bairro, apresentando o total de matrículas em cada bairro. Também foi exibido o total de matrículas em Goiás, o número de escolas únicas e o número de bairros nos municípios de Goiás.

In [ ]:
#Goiás

# Agrupa os dados por município e bairro, somando as matrículas na Educação Básica
mat_bairros = dados_matriculas.groupby(['Município', 'Bairro'])['Matrículas Educação Básica'].sum().reset_index()

# Agrupa os dados apenas por bairro, somando as matrículas na Educação Básica
mat_bairros_print = dados_matriculas.groupby(['Bairro'])['Matrículas Educação Básica'].sum().reset_index()

# Exibe o total de matrículas, escolas e bairros em Goiás (exceto Goiânia)
print(f"Ao todo, {mat_bairros['Matrículas Educação Básica'].sum()} matrículas estão divididas nas {dados_matriculas['Nome da escola'].nunique()} escolas nos {mat_bairros['Bairro'].nunique()} bairros de {dados_matriculas['Município'].nunique()} municípios de Goiás (exceto Goiânia).")

# Exporta os dados do dataframe 'mat_bairros' para um arquivo CSV
mat_bairros.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goias - Total de matrículas por bairro.csv', index=False)

# Exibe o dataframe 'mat_bairros'
mat_bairros

Ao todo, 1166234 matrículas estão divididas nas 3782 escolas nos 1408 bairros de 245 municípios de Goiás (exceto Goiânia).

,Município,Bairro,Matrículas Educação Básica
0,Abadia de Goiás,CENTRO,302
1,Abadia de Goiás,JARDIM FLORITA,137
2,Abadia de Goiás,RESIDENCIAL JARDIM FLORITA,423
3,Abadia de Goiás,RESIDENCIAL PAINEIRAS,360
4,Abadia de Goiás,SETOR PARQUE IZABEL,634
...,...,...,...
2045,Águas Lindas de Goiás,SETOR 08,843
2046,Águas Lindas de Goiás,SETOR 11,562
2047,Águas Lindas de Goiás,SETOR 14,2030
2048,Águas Lindas de Goiás,SETOR 2,831
2049,Águas Lindas de Goiás,SETOR COIMBRA,1591

Idem, agora para Goiânia:

In [ ]:
#Goiânia

# Agrupa os dados por município e bairro, somando as matrículas na Educação Básica
mat_bairros = dados_matriculas.groupby(['Município', 'Bairro'])['Matrículas Educação Básica'].sum().reset_index()

# Agrupa os dados apenas por bairro, somando as matrículas na Educação Básica
mat_bairros_print = dados_matriculas.groupby(['Bairro'])['Matrículas Educação Básica'].sum().reset_index()

# Exibe o total de matrículas, escolas e bairros em Goiás (exceto Goiânia)
print(f"Ao todo, {mat_bairros['Matrículas Educação Básica'].sum()} matrículas estão divididas nas {dados_matriculas['Nome da escola'].nunique()} escolas nos {mat_bairros['Bairro'].nunique()} bairros de {dados_matriculas['Município'].nunique()} municípios de Goiás (exceto Goiânia).")

# Exporta os dados do dataframe 'mat_bairros' para um arquivo CSV
mat_bairros.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goias - Total de matrículas por bairro.csv', index=False)

# Exibe o dataframe 'mat_bairros'
mat_bairros

C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_25840\1630920333.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mat_bairros = dados_matriculas.groupby(['Município', 'Bairro'])['Matrículas Educação Básica', 'Matrículas Educação Infantil', 'Matrículas Ensino Fundamental',

,Município,Bairro,Matrículas Educação Básica,Matrículas Educação Infantil,Matrículas Ensino Fundamental,Matrículas Ensino_Médio,Matrículas Educação Profissional Técnico,Matrículas Educação de Jovens e Adultos,Matrículas Educação Especial
0,Goiânia,AEROVIARIO,1048,168,503,81,206,90,21
1,Goiânia,AGUA BRANCA,355,135,201,0,0,19,5
2,Goiânia,ALTO DA GLORIA,1123,503,561,0,0,59,22
3,Goiânia,ANDREIA CRISTINA,774,0,774,0,0,0,4
4,Goiânia,ANHANGUERA,302,220,82,0,0,0,3
...,...,...,...,...,...,...,...,...,...
309,Goiânia,VILA SANTA ISABEL,97,0,0,0,0,97,97
310,Goiânia,VILA SANTA RITA - 5ª ETAPA,144,0,144,0,0,0,0
311,Goiânia,VILA SAO JOAO,401,162,239,0,0,0,6
312,Goiânia,VILA SAO LUIZ,0,0,0,0,0,0,0
313,Goiânia,VILLAGE ATALAIA,184,184,0,0,0,0,4

## Censo Superior

Para a análise da Educação Superior em Goiás, utilizamos os microdados do Censo da Educação Superior 2021, disponibilizados pelo Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (Inep), do Ministério da Educação (MEC). O arquivo "MICRODADOS_CADASTRO_IES_2021.CSV" foi lido e carregado no dataframe "censo_edu_superior". A seguir, são exibidas as primeiras duas linhas desse dataframe.

In [ ]:
# Leitura dos microdados do Censo da Educação Superior 2021
censo_edu_superior = pd.read_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Dados\Microdados do Censo da Educação Superior 2021\dados\MICRODADOS_CADASTRO_IES_2021.CSV',
                                 sep=';', encoding='latin-1', low_memory=False)

# Exibição das primeiras duas linhas do dataframe
censo_edu_superior.head(2)

,NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,...,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA,CO_PROJETO,CO_LOCAL_OFERTA,NO_LOCAL_OFERTA
0,2021,Centro-Oeste,5,Mato Grosso,MT,51,Cuiabá,5103403,1,Centro-Sul Mato-grossense,...,390,48,5,113,1593,35,6,2111801,105340,Campus Universitário de Cuiabá
1,2021,Centro-Oeste,5,Distrito Federal,DF,53,Brasília,5300108,1,Distrito Federal,...,416,57,8,406,2496,143,10,2111801,4229,Campus Universitário Darcy Ribeiro

Para a análise da Educação Superior em Goiás, foram aplicados filtros nos dados do dataframe "censo_edu_superior". Foram selecionadas apenas as instituições de ensino localizadas em Goiás (exceto Goiânia). Em seguida, foram escolhidas as colunas relevantes para a análise, incluindo o município da instituição, o nome da instituição, o bairro, a organização acadêmica e a categoria administrativa.

In [ ]:
# Filtragem das instituições de ensino em Goiás (exceto Goiânia)
censo_edu_superior = censo_edu_superior[censo_edu_superior['NO_UF_IES'] == 'Goiás']
censo_edu_superior = censo_edu_superior[censo_edu_superior['NO_MUNICIPIO_IES'] != 'Goiânia']

# Seleção das colunas relevantes
censo_superior = censo_edu_superior[['NO_MUNICIPIO_IES', 'NO_IES', 'NO_BAIRRO_IES', 'TP_ORGANIZACAO_ACADEMICA', 'TP_CATEGORIA_ADMINISTRATIVA']]

# Mapeamento das legendas para a coluna 'TP_ORGANIZACAO_ACADEMICA'
legenda_organizacao_acad = {
    1: 'Universidade',
    2: 'Centro Universitário',
    3: 'Faculdade',
    4: 'Instituto Federal de Educação, Ciência e Tecnologia',
    5: 'Centro Federal de Educação Tecnológica',
}
censo_superior['TP_ORGANIZACAO_ACADEMICA'] = censo_superior['TP_ORGANIZACAO_ACADEMICA'].map(legenda_organizacao_acad)

# Mapeamento das legendas para a coluna 'TP_CATEGORIA_ADMINISTRATIVA'
legenda_cat_adm = {
    1: 'Pública Federal',
    2: 'Pública Estadual',
    3: 'Pública Municipal',
    4: 'Privada com fins lucrativos',
    5: 'Privada sem fins lucrativos',
    6: 'Privada - Particular em sentido estrito',
    7: 'Especial',
    8: 'Privada comunitária',
    9: 'Privada confessional'
}
censo_superior['TP_CATEGORIA_ADMINISTRATIVA'] = censo_superior['TP_CATEGORIA_ADMINISTRATIVA'].map(legenda_cat_adm)

# Renomeação das colunas
censo_superior.columns = ['Município', 'Nome do IES', 'Bairro', 'Organização acadêmica', 'Categoria administrativa']

# Exibição das primeiras duas linhas do dataframe
censo_superior.head(2)

Os dados do ensino superior em Goiás foram organizados e salvos no arquivo "Goiás - Ensino superior - total.csv". O dataframe "censo_superior" foi ordenado por município em ordem crescente. Em seguida, é exibida a quantidade total de instituições de ensino superior em Goiás, considerando faculdades, universidades e outras categorias.

In [ ]:
# Ordenação dos dados por município
censo_superior = censo_superior.sort_values(by='Município', ascending=True)

# Salvando os dados no arquivo CSV
censo_superior.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goiás - Ensino superior - total.csv', index=False)

# Exibição do total de instituições de ensino superior em Goiás
print(f"Ao todo, o estado de Goiás tem {censo_superior['Nome do IES'].nunique()} instituições de ensino superior (faculdades, universidades, entre outros).")

# Exibição do dataframe
censo_superior

Ao todo, o estado de Goiás tem 82 instituições de ensino superior (faculdades, universidades, entre outros.

,Município,Nome do IES,Bairro,Organização acadêmica,Categoria administrativa
367,Anicuns,FACULDADE DE ANICUNS,Centro,Faculdade,Pública Municipal
2199,Anápolis,Faculdade ICTQ/PGE,Setor Central,Faculdade,Privada com fins lucrativos
433,Anápolis,FACULDADE CATÓLICA DE ANÁPOLIS,Cidade Jardim,Faculdade,Privada sem fins lucrativos
176,Anápolis,Universidade Evangélica de Goiás,Cidade Universitária,Universidade,Privada sem fins lucrativos
1671,Anápolis,FACULDADE ANHANGUERA DE ANÁPOLIS,Centro,Faculdade,Privada com fins lucrativos
...,...,...,...,...,...
740,Valparaíso de Goiás,FACULDADE DE CIÊNCIAS E EDUCAÇÃO SENA AIRES,Chácaras Anhanguera,Faculdade,Privada com fins lucrativos
1186,Valparaíso de Goiás,FACULDADE ANHANGUERA DE VALPARAÍSO,Parque Rio Branco,Faculdade,Privada com fins lucrativos
631,Valparaíso de Goiás,INSTITUTO DE CIÊNCIAS SOCIAIS E HUMANAS,Jardim Oriente,Faculdade,Privada com fins lucrativos
2118,Águas Lindas de Goiás,Faculdade FILOS,Jardim Pérola da Barragem II,Faculdade,Privada com fins lucrativos
1412,Águas Lindas de Goiás,FACULDADE MAUÁ DE GOIÁS,Mansões Village,Faculdade,Privada com fins lucrativos

Os dados do ensino superior em Goiás foram agrupados por município para obter o total de universidades em cada cidade. O resultado foi armazenado no arquivo "Goiás - Ensino superior - total por município.csv". Em seguida, é exibido o total de instituições de ensino superior em Goiás, considerando todas as cidades, exceto Goiânia, e o número de municípios onde essas instituições estão localizadas.

In [ ]:
# Goiás por cidade

# Agrupamento dos dados por município e contagem do total de universidades
total_ies = censo_superior.groupby(['Município']).size().reset_index(name='Total de universidades')

# Ordenação dos dados por total de universidades em ordem decrescente
total_ies = total_ies.sort_values(by='Total de universidades', ascending=False)

# Salvando os dados no arquivo CSV
total_ies.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goiás - Ensino superior - total por município.csv', index=False)

# Exibição do total de instituições de ensino superior em Goiás e o número de municípios
print(f"Ao todo, o estado de Goiás tem {total_ies['Total de universidades'].sum()} instituições de ensino superior, espalhadas

Ao todo, o estado de Goiás tem 82 instituições de ensino superior, espalhadas por 37 municípios - exceto Goiânia.

                   Município  Total de universidades
1                   Anápolis                      11
2       Aparecida de Goiânia                       6
4                    Catalão                       5
15                 Itumbiara                       5
28                 Rio Verde                       4
7                    Formosa                       4
17                     Jataí                       4
35       Valparaíso de Goiás                       3
19                  Luziânia                       3
26                 Porangatu                       3
36     Águas Lindas de Goiás                       2
20                  Mineiros                       2
27              Quirinópolis                       2
22        Palmeiras de Goiás                       2
31            Senador Canedo                       2
33                  Trindade                       2
3               Caldas Novas                       2
29                 Rubiataba                       1
24              Pires do Rio                       1
32  São Luís de Montes Belos                       1
34                    Uruaçu                       1
25                 Pontalina                       1
30  Santa Terezinha de Goiás                       1
0                    Anicuns                       1
23               Piracanjuba                       1
21                 Novo Gama                       1
16                   Jaraguá                       1
14                Itapuranga                       1
13                  Itaberaí                       1
12                     Iporá                       1
11                   Inhumas                       1
10                   Indiara                       1
9                   Goiatuba                       1
8                  Goianésia                       1
6                 Cristalina                       1
5                      Ceres                       1
18                   Jussara                       1

Os dados do ensino superior em Goiânia foram agrupados por bairro para obter o total de universidades em cada região. O resultado foi armazenado no arquivo "Ensino superior - total por bairro.csv". Em seguida, é exibido o total de instituições de ensino superior em Goiânia, considerando cada bairro da cidade.

In [ ]:
# Goiânia por bairro

# Agrupamento dos dados por bairro e contagem do total de universidades
total_ies = censo_superior.groupby(['Bairro']).size().reset_index(name='Total de universidades')

# Ordenação dos dados por total de universidades em ordem decrescente
total_ies = total_ies.sort_values(by='Total de universidades', ascending=False)

# Salvando os dados no arquivo CSV
total_ies.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Ensino superior - total por bairro.csv', index=False)

# Exibição do dataframe
total_ies

                                     Bairro  Total de universidades
9                               Setor Bueno                       5
16                              Setor Oeste                       4
14                Setor Leste Universitário                       2
4                           Jardim Vila Boa                       2
10                            Setor Central                       2
12                            Setor Coimbra                       2
0                          Campus Samambaia                       1
21                            Vila João Vaz                       1
20  Sítio de Recreio Mansões Bernardo Sayão                       1
19                                Setor Sul                       1
18                       Setor Sol Nascente                       1
17                     Setor Pedro Ludovico                       1
15                    Setor Leste Vila Nova                       1
11                       Setor Centro Oeste                       1
13                                Setor Jaó                       1
1                             Cidade Jardim                       1
8                       SETOR UNIVERSITÁRIO                       1
7                           Parque Amazônia                       1
6                             Morada do Sol                       1
5                             Jardim da Luz                       1
3                           Jardim Planalto                       1
2                             Jardim Europa                       1
22                             Vila Paraíso                       1

Os dados do ensino superior em Goiás foram agrupados por município e organização acadêmica para obter o total de universidades em cada categoria. O resultado foi armazenado no arquivo "Goiás - Ensino superior - total por organização acadêmica.csv". Em seguida, é exibido o total de universidades em Goiás, exceto Goiânia, considerando cada categoria de organização acadêmica.

In [ ]:
# Goiás

ies_org_acad = censo_superior.groupby(['Município', 'Organização acadêmica']).size().reset_index(name='Total de universidades')
ies_org_acad = ies_org_acad.sort_values(by='Município', ascending=False)

## para print
ies_org_acad_print = censo_superior.groupby(['Organização acadêmica']).size().reset_index(name='Total de universidades')
ies_org_acad_print = ies_org_acad_print.sort_values(by='Total de universidades', ascending=False)
for index, row in ies_org_acad_print.iterrows():
    print(f"O total de universidades por organização acadêmica em Goiás (exceto Goiânia) é: {row['Total de universidades']} de {row['Organização acadêmica']}s.")
ies_org_acad.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goiás - Ensino superior - total por organização acadêmica.csv', index=False)
ies_org_acad

O total de universidades por organização acadêmica em Goiás (exceto Goiânia) é: 70 de Faculdades.
O total de universidades por organização acadêmica em Goiás (exceto Goiânia) é: 7 de Centro Universitários.
O total de universidades por organização acadêmica em Goiás (exceto Goiânia) é: 5 de Universidades.

                   Município Organização acadêmica  Total de universidades
44     Águas Lindas de Goiás             Faculdade                       2
43       Valparaíso de Goiás             Faculdade                       3
42                    Uruaçu             Faculdade                       1
41                  Trindade             Faculdade                       1
40                  Trindade  Centro Universitário                       1
39  São Luís de Montes Belos  Centro Universitário                       1
38            Senador Canedo             Faculdade                       2
37  Santa Terezinha de Goiás             Faculdade                       1
36                 Rubiataba             Faculdade                       1
35                 Rio Verde          Universidade                       1
34                 Rio Verde             Faculdade                       3
33              Quirinópolis             Faculdade                       2
32                 Porangatu             Faculdade                       3
31                 Pontalina             Faculdade                       1
30              Pires do Rio             Faculdade                       1
29               Piracanjuba             Faculdade                       1
28        Palmeiras de Goiás             Faculdade                       2
27                 Novo Gama             Faculdade                       1
26                  Mineiros             Faculdade                       1
25                  Mineiros  Centro Universitário                       1
23                  Luziânia  Centro Universitário                       1
24                  Luziânia             Faculdade                       2
22                   Jussara             Faculdade                       1
21                     Jataí          Universidade                       1
20                     Jataí             Faculdade                       3
19                   Jaraguá             Faculdade                       1
18                 Itumbiara             Faculdade                       5
17                Itapuranga             Faculdade                       1
16                  Itaberaí             Faculdade                       1
15                     Iporá             Faculdade                       1
14                   Inhumas             Faculdade                       1
13                   Indiara             Faculdade                       1
12                  Goiatuba  Centro Universitário                       1
11                 Goianésia             Faculdade                       1
10                   Formosa             Faculdade                       4
9                 Cristalina             Faculdade                       1
8                      Ceres             Faculdade                       1
7                    Catalão          Universidade                       1
6                    Catalão             Faculdade                       4
5               Caldas Novas             Faculdade                       2
4       Aparecida de Goiânia             Faculdade                       4
3       Aparecida de Goiânia  Centro Universitário                       2
2                   Anápolis          Universidade                       2
1                   Anápolis             Faculdade                       9
0                    Anicuns             Faculdade                       1

In [ ]:
# Goiânia

# Agrupamento dos dados por município e organização acadêmica e contagem do total de universidades
ies_org_acad = censo_superior.groupby(['Município', 'Organização acadêmica']).size().reset_index(name='Total de universidades')

# Ordenação dos dados por município em ordem decrescente
ies_org_acad = ies_org_acad.sort_values(by='Município', ascending=False)

# Salvando os dados no arquivo CSV
ies_org_acad.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goiás - Ensino superior - total por organização acadêmica.csv', index=False)

# Exibição do total de universidades por organização acadêmica em Goiás (exceto Goiânia)
ies_org_acad_print = censo_superior.groupby(['Organização acadêmica']).size().reset_index(name='Total de universidades')
ies_org_acad_print = ies_org_acad_print.sort_values(by='Total de universidades', ascending=False)
for index, row in ies_org_acad_print.iterrows():
    print(f"O total de universidades por organização acadêmica em Goiás (exceto Goiânia) é: {row['Total de universidades']} de {row['Organização acadêmica']}s.")

# Exibição do dataframe
ies_org_acad

Idem, agora para Goiânia:

In [ ]:
# Goiânia

# Agrupamento dos dados por organização acadêmica e contagem do total de universidades
ies_org_acad = censo_superior.groupby(['Organização acadêmica']).size().reset_index(name='Total de universidades')

# Ordenação dos dados por total de universidades em ordem decrescente
ies_org_acad = ies_org_acad.sort_values(by='Total de universidades', ascending=False)

# Salvando os dados no arquivo CSV
ies_org_acad.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Ensino superior - total por organização acadêmica.csv', index=False)

# Exibição do total de universidades por organização acadêmica em Goiânia
for index, row in ies_org_acad.iterrows():
    print(f"O total de universidades por organização acadêmica é: {row['Total de universidades']}  {row['Organização acadêmica']}s.")

# Exibição do dataframe
ies_org_acad

O total de universidades por organização acadêmica é: 23  Faculdades.
O total de universidades por organização acadêmica é: 7  Centro Universitários.
O total de universidades por organização acadêmica é: 2  Instituto Federal de Educação, Ciência e Tecnologias.
O total de universidades por organização acadêmica é: 2  Universidades.

                               Organização acadêmica  Total de universidades
1                                          Faculdade                      23
0                               Centro Universitário                       7
2  Instituto Federal de Educação, Ciência e Tecno...                       2
3                                       Universidade                       2

In [ ]:
# Goiás

# Agrupamento dos dados por município e categoria administrativa e contagem do total de universidades
ies_cat_adm = censo_superior.groupby(['Município', 'Categoria administrativa']).size().reset_index(name='Total de universidades')

# Ordenação dos dados por total de universidades em ordem decrescente
ies_cat_adm = ies_cat_adm.sort_values(by='Total de universidades', ascending=False)

# Salvando os dados no arquivo CSV
ies_cat_adm.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Goiás - Ensino superior - total por categoria administrativa.csv', index=False)

# Agrupamento dos dados por categoria administrativa para exibição
ies_cat_adm_print = censo_superior.groupby(['Categoria administrativa']).size().reset_index(name='Total de universidades')
ies_cat_adm_print = ies_cat_adm_print.sort_values(by='Total de universidades', ascending=False)

# Exibição do total de universidades por categoria administrativa em Goiás (exceto Goiânia)
for index, row in ies_cat_adm_print.iterrows():
    print(f"O total de universidades por categoria administrativa em Goiás (exceto Goiânia) é: {row['Total de universidades']} de {row['Categoria administrativa']}s.")

# Exibição do dataframe
ies_cat_adm

O total de universidades por organização categoria administrativa em Goiás (exceto Goiânia) é: 64 de Privada com fins lucrativoss.
O total de universidades por organização categoria administrativa em Goiás (exceto Goiânia) é: 11 de Privada sem fins lucrativoss.
O total de universidades por organização categoria administrativa em Goiás (exceto Goiânia) é: 4 de Pública Municipals.
O total de universidades por organização categoria administrativa em Goiás (exceto Goiânia) é: 2 de Pública Federals.
O total de universidades por organização categoria administrativa em Goiás (exceto Goiânia) é: 1 de Pública Estaduals.

,Município,Categoria administrativa,Total de universidades
1,Anápolis,Privada com fins lucrativos,6
2,Anápolis,Privada sem fins lucrativos,4
4,Aparecida de Goiânia,Privada com fins lucrativos,4
7,Catalão,Privada com fins lucrativos,4
19,Itumbiara,Privada com fins lucrativos,4
11,Formosa,Privada com fins lucrativos,4
45,Valparaíso de Goiás,Privada com fins lucrativos,3
33,Porangatu,Privada com fins lucrativos,3
22,Jataí,Privada com fins lucrativos,3
25,Luziânia,Privada com fins lucrativos,3
46,Águas Lindas de Goiás,Privada com fins lucrativos,2
34,Quirinópolis,Privada com fins lucrativos,2
29,Palmeiras de Goiás,Privada com fins lucrativos,2
43,Trindade,Privada com fins lucrativos,2
6,Caldas Novas,Privada com fins lucrativos,2
5,Aparecida de Goiânia,Privada sem fins lucrativos,2
35,Rio Verde,Privada com fins lucrativos,2
32,Pontalina,Privada sem fins lucrativos,1
31,Pires do Rio,Privada com fins lucrativos,1
39,Santa Terezinha de Goiás,Privada com fins lucrativos,1
36,Rio Verde,Privada sem fins lucrativos,1
37,Rio Verde,Pública Municipal,1
38,Rubiataba,Privada com fins lucrativos,1
40,Senador Canedo,Privada com fins lucrativos,1
41,Senador Canedo,Privada sem fins lucrativos,1
42,São Luís de Montes Belos,Privada com fins lucrativos,1
44,Uruaçu,Privada com fins lucrativos,1
30,Piracanjuba,Privada com fins lucrativos,1
0,Anicuns,Pública Municipal,1
28,Novo Gama,Privada com fins lucrativos,1
27,Mineiros,Pública Municipal,1
3,Anápolis,Pública Estadual,1
8,Catalão,Pública Federal,1
9,Ceres,Privada com fins lucrativos,1
10,Cristalina,Privada com fins lucrativos,1
12,Goianésia,Privada sem fins lucrativos,1
13,Goiatuba,Pública Municipal,1
14,Indiara,Privada com fins lucrativos,1
15,Inhumas,Privada com fins lucrativos,1
16,Iporá,Privada com fins lucrativos,1
17,Itaberaí,Privada com fins lucrativos,1
18,Itapuranga,Privada com fins lucrativos,1
20,Itumbiara,Privada sem fins lucrativos,1
21,Jaraguá,Privada com fins lucrativos,1
24,Jussara,Privada com fins lucrativos,1
26,Mineiros,Privada com fins lucrativos,1
23,Jataí,Pública Federal,1

Idem, agora para Goiânia:

In [ ]:
# Goiânia

# Agrupamento dos dados por categoria administrativa e contagem do total de universidades
ies_cat_adm = censo_superior.groupby(['Categoria administrativa']).size().reset_index(name='Total de universidades')

# Ordenação dos dados por total de universidades em ordem decrescente
ies_cat_adm = ies_cat_adm.sort_values(by='Total de universidades', ascending=False)

# Salvando os dados no arquivo CSV
ies_cat_adm.to_csv('I:\Freelas\Anuário de Dados - Goiás\Educação\Ensino superior - total por categoria administrativa.csv', index=False)

# Exibição do total de universidades por categoria administrativa em Goiânia
for index, row in ies_cat_adm.iterrows():
    print(f"O total de universidades por categoria administrativa é: {row['Total de universidades']}  {row['Categoria administrativa']}s.")

# Exibição do dataframe
ies_cat_adm

O total de universidades por categoria administrativa a é: 23  Privada com fins lucrativoss.
O total de universidades por categoria administrativa a é: 8  Privada sem fins lucrativoss.
O total de universidades por categoria administrativa a é: 3  Pública Federals.

      Categoria administrativa  Total de universidades
0  Privada com fins lucrativos                      23
1  Privada sem fins lucrativos                       8
2              Pública Federal                       3

### IDEB


Utilizando as bases de dados divulgadas pelo Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (INEP), faremos uma análise dos índices do Índice de Desenvolvimento da Educação Básica (IDEB) no Brasil, nos níveis de Ensino Fundamental - Anos Iniciais, Ensino Fundamental - Anos Finais e Ensino Médio.

##### Anos Iniciais

Utilizando as bases de dados do IDEB para o Ensino Fundamental - Anos Iniciais, faremos uma análise das posições do IDEB por ano e por rede de ensino. O objetivo é identificar a variação da posição do IDEB ao longo dos anos e verificar o desempenho das redes de ensino em relação aos demais municípios.

In [ ]:
# Leitura dos dados do IDEB - Ensino Fundamental - Anos Iniciais
ideb_anos_iniciais = pd.read_csv(r'I:\Freelas\Anuário de Dados - Goiás\Educação\bases limpas\IDEB - Ensino Fundamental Regular - Anos Iniciais.csv')

# Agrupamento dos dados por rede de ensino
grupo_rede = ideb_anos_iniciais.groupby('Rede')
dataframes_separados = [grupo for _, grupo in grupo_rede]
dataframes_separados_por_rede_e_ano = []

# Separação dos dataframes por ano dentro de cada rede de ensino
for df_rede in dataframes_separados:
    grupo_ano = df_rede.groupby('Ano')
    dataframes_separados_por_ano = [grupo for _, grupo in grupo_ano]
    dataframes_separados_por_rede_e_ano.extend(dataframes_separados_por_ano)
dataframes_com_posicao = []

# Cálculo da posição do IDEB e criação de novos dataframes com as posições
for df_grupo in dataframes_separados_por_rede_e_ano:
    df_grupo['Posição IDEB'] = df_grupo['Nota IDEB'].rank(ascending=False, method='min')
    dataframes_com_posicao.append(df_grupo)

# Concatenação dos dataframes com as posições
df_posicao_ideb = pd.concat(dataframes_com_posicao).reset_index(drop=True)
df_posicao_ideb.replace([np.inf, -np.inf], np.nan, inplace=True)
df_posicao_ideb['Posição IDEB'] = df_posicao_ideb['Posição IDEB'].astype(float).fillna(0).astype(int)

# Cálculo do delta de posição entre anos para cada município e rede de ensino
df_posicao_ideb['Delta Posição'] = df_posicao_ideb.groupby(['Rede', 'Município'])['Posição IDEB'].diff()
df_posicao_ideb.replace([np.inf, -np.inf], np.nan, inplace=True)
df_posicao_ideb['Delta Posição'] = df_posicao_ideb['Delta Posição'].astype(float).fillna(0).astype(int)
df_posicao_ideb['Delta Posição'] = df_posicao_ideb['Delta Posição'].apply(lambda x: -x if x > 0 else abs(x))

df_posicao_ideb

,Ensino,Ano,UF,Município,Rede,Nota IDEB,Posição IDEB,Delta Posição
0,Ensino Fundamental Regular - Anos Iniciais,2005,RO,Alta Floresta D'Oeste,Estadual,"3,5",1569,0
1,Ensino Fundamental Regular - Anos Iniciais,2005,RO,Ariquemes,Estadual,4,1069,0
2,Ensino Fundamental Regular - Anos Iniciais,2005,RO,Cabixi,Estadual,"4,1",961,0
3,Ensino Fundamental Regular - Anos Iniciais,2005,RO,Cacoal,Estadual,"3,8",1277,0
4,Ensino Fundamental Regular - Anos Iniciais,2005,RO,Cerejeiras,Estadual,"4,1",961,0
...,...,...,...,...,...,...,...,...
130199,Ensino Fundamental Regular - Anos Iniciais,2021,GO,Vianópolis,Pública,6,1514,-560
130200,Ensino Fundamental Regular - Anos Iniciais,2021,GO,Vicentinópolis,Pública,"5,9",1747,-382
130201,Ensino Fundamental Regular - Anos Iniciais,2021,GO,Vila Boa,Pública,"5,3",3133,564
130202,Ensino Fundamental Regular - Anos Iniciais,2021,GO,Vila Propício,Pública,"5,9",1747,3673
130203,Ensino Fundamental Regular - Anos Iniciais,2021,DF,Brasília,Pública,"5,9",1747,324

O código apresentado realiza o cálculo da posição do IDEB, criação de dataframes com as posições e deltas de posição, e filtra os resultados específicos para o município de Goiânia e outras cidades de Goiás. O dataframe resultante df_posicao_ideb_goiania contém as informações das posições e deltas de posição para Goiânia nos Anos Iniciais do Ensino Fundamental.

In [ ]:
#Goiânia
# Filtrar os dados do dataframe df_posicao_ideb apenas para o município de Goiânia
df_posicao_ideb_goiania = df_posicao_ideb[df_posicao_ideb['Município'] == 'Goiânia']

# Salvar o dataframe filtrado em um arquivo CSV
df_posicao_ideb_goiania.to_csv(r'I:\Freelas\Anuário de Dados - Goiás\Educação\IDEB - Ensino Fundamental Regular - Anos Iniciais.csv', index=False)

# Exibir as duas primeiras linhas do dataframe df_posicao_ideb_goiania
df_posicao_ideb_goiania.head(2)

,Ensino,Ano,UF,Município,Rede,Nota IDEB,Posição IDEB,Delta Posição
3367,Ensino Fundamental Regular - Anos Iniciais,2005,GO,Goiânia,Estadual,4,1069,0
6848,Ensino Fundamental Regular - Anos Iniciais,2007,GO,Goiânia,Estadual,"4,1",1534,-465

In [ ]:
#Goiás
# Filtrar os dados do dataframe df_posicao_ideb para conter apenas as informações do estado de Goiás (exceto Goiânia)
df_posicao_ideb_goias = df_posicao_ideb[df_posicao_ideb['UF'] == 'GO']
df_posicao_ideb_goias = df_posicao_ideb_goias[df_posicao_ideb['Município'] != 'Goiânia']

# Ordenar o dataframe df_posicao_ideb_goias por Município, Rede e Ano em ordem crescente
df_posicao_ideb_goias = df_posicao_ideb_goias.sort_values(by=['Município', 'Rede', 'Ano'], ascending=True)

# Salvar o dataframe df_posicao_ideb_goias em um arquivo CSV específico para o IDEB nos Anos Iniciais do Ensino Fundamental em Goiás
df_posicao_ideb_goias.to_csv(r'I:\Freelas\Anuário de Dados - Goiás\Educação\Goiás - IDEB - Ensino Fundamental Regular - Anos Iniciais.csv', index=False)

# Exibir as duas primeiras linhas do dataframe df_posicao_ideb_goias
df_posicao_ideb_goias.head(2)

C:\Users\Renato Crozatti\AppData\Local\Temp\ipykernel_9356\3342488523.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_posicao_ideb_goias = df_posicao_ideb_goias[df_posicao_ideb['Município'] != 'Goiânia']

,Ensino,Ano,UF,Município,Rede,Nota IDEB,Posição IDEB,Delta Posição
4657,Ensino Fundamental Regular - Anos Finais,2005,GO,Abadia de Goiás,Estadual,"3,4",2111,0
9557,Ensino Fundamental Regular - Anos Finais,2007,GO,Abadia de Goiás,Estadual,"2,9",3790,-1679

Utilizando as informações disponibilizadas pelo IDEB (Índice de Desenvolvimento da Educação Básica), foram analisados os dados referentes ao Ensino Fundamental Regular nos Anos Finais em Goiás. O dataframe df_posicao_ideb foi construído com as posições do IDEB por rede de ensino, município e ano. Foram realizados cálculos para determinar a posição do IDEB e o delta de posição em relação ao ano anterior. O resultado final é apresentado no dataframe df_posicao_ideb.

In [ ]:
# Leitura do arquivo CSV contendo os dados do IDEB - Ensino Fundamental Regular - Anos Finais
ideb_anos_finais = pd.read_csv(r'I:\Freelas\Anuário de Dados - Goiás\Educação\bases limpas\IDEB - Ensino Fundamental Regular - Anos Finais.csv')

# Agrupamento dos dados por rede de ensino
grupo_rede = ideb_anos_finais.groupby('Rede')
dataframes_separados = [grupo for _, grupo in grupo_rede]
dataframes_separados_por_rede_e_ano = []

# Separação dos dataframes por rede de ensino e ano
for df_rede in dataframes_separados:
    grupo_ano = df_rede.groupby('Ano')
    dataframes_separados_por_ano = [grupo for _, grupo in grupo_ano]
    dataframes_separados_por_rede_e_ano.extend(dataframes_separados_por_ano)

dataframes_com_posicao = []

# Cálculo da posição do IDEB por grupo de dados
for df_grupo in dataframes_separados_por_rede_e_ano:
    df_grupo['Posição IDEB'] = df_grupo['Nota IDEB'].rank(ascending=False, method='min')
    dataframes_com_posicao.append(df_grupo)

# Concatenação dos dataframes com a posição do IDEB
df_posicao_ideb = pd.concat(dataframes_com_posicao).reset_index(drop=True)
df_posicao_ideb.replace([np.inf, -np.inf], np.nan, inplace=True)
df_posicao_ideb['Posição IDEB'] = df_posicao_ideb['Posição IDEB'].astype(float).fillna(0).astype(int)

# Cálculo do delta de posição do IDEB em relação ao ano anterior
df_posicao_ideb['Delta Posição'] = df_posicao_ideb.groupby(['Rede', 'Município'])['Posição IDEB'].diff()
df_posicao_ideb.replace([np.inf, -np.inf], np.nan, inplace=True)
df_posicao_ideb['Delta Posição'] = df_posicao_ideb['Delta Posição'].astype(float).fillna(0).astype(int)
df_posicao_ideb['Delta Posição'] = df_posicao_ideb['Delta Posição'].apply(lambda x: -x if x > 0 else abs(x))

# Exibição do resultado final
df_posicao_ideb

,Ensino,Ano,UF,Município,Rede,Nota IDEB,Posição IDEB,Delta Posição
0,Ensino Fundamental Regular - Anos Finais,2005,RO,Alta Floresta D'Oeste,Estadual,"3,5",1865,0
1,Ensino Fundamental Regular - Anos Finais,2005,RO,Ariquemes,Estadual,"3,6",1631,0
2,Ensino Fundamental Regular - Anos Finais,2005,RO,Cabixi,Estadual,"3,8",1168,0
3,Ensino Fundamental Regular - Anos Finais,2005,RO,Cacoal,Estadual,"3,5",1865,0
4,Ensino Fundamental Regular - Anos Finais,2005,RO,Cerejeiras,Estadual,"3,5",1865,0
...,...,...,...,...,...,...,...,...
129366,Ensino Fundamental Regular - Anos Finais,2021,GO,Vianópolis,Pública,"5,7",274,-155
129367,Ensino Fundamental Regular - Anos Finais,2021,GO,Vicentinópolis,Pública,"5,5",565,-446
129368,Ensino Fundamental Regular - Anos Finais,2021,GO,Vila Boa,Pública,5,1937,784
129369,Ensino Fundamental Regular - Anos Finais,2021,GO,Vila Propício,Pública,"5,6",395,72
129370,Ensino Fundamental Regular - Anos Finais,2021,DF,Brasília,Pública,"4,9",2256,465

Foram realizadas análises nos dados para obter a posição do IDEB por município, rede de ensino e ano. Em seguida, os resultados foram filtrados para o município de Goiânia e para o estado de Goiás, excluindo Goiânia. Os dados resultantes foram salvos em arquivos CSV e apresentados como os primeiros registros.

In [ ]:
# Goiânia
# Filtragem dos dados do IDEB para o município de Goiânia
df_posicao_ideb_goiania = df_posicao_ideb[df_posicao_ideb['Município'] == 'Goiânia']
df_posicao_ideb_goiania.to_csv(r'I:\Freelas\Anuário de Dados - Goiás\Educação\IDEB - Ensino Fundamental Regular - Anos Finais.csv', index=False)
df_posicao_ideb_goiania.head(2)

,Ensino,Ano,UF,Município,Rede,Nota IDEB,Posição IDEB,Delta Posição
4748,Ensino Fundamental Regular - Anos Finais,2005,GO,Goiânia,Estadual,"3,4",2111,0
9648,Ensino Fundamental Regular - Anos Finais,2007,GO,Goiânia,Estadual,"3,5",2528,-417

In [ ]:
# Goiás
# Filtragem dos dados do IDEB para o estado de Goiás, excluindo o município de Goiânia
df_posicao_ideb_goias = df_posicao_ideb[df_posicao_ideb['UF'] == 'GO']
df_posicao_ideb_goias = df_posicao_ideb_goias[df_posicao_ideb_goias['Município'] != 'Goiânia']
df_posicao_ideb_goias = df_posicao_ideb_goias.sort_values(by=['Município', 'Rede', 'Ano'], ascending=True)
df_posicao_ideb_goias.to_csv(r'I:\Freelas\Anuário de Dados - Goiás\Educação\Goiás - IDEB - Ensino Fundamental Regular - Anos Finais.csv', index=False)
df_posicao_ideb_goias.head(2)

,Ensino,Ano,UF,Município,Rede,Nota IDEB,Posição IDEB,Delta Posição
4657,Ensino Fundamental Regular - Anos Finais,2005,GO,Abadia de Goiás,Estadual,"3,4",2111,0
9557,Ensino Fundamental Regular - Anos Finais,2007,GO,Abadia de Goiás,Estadual,"2,9",3790,-1679

O Índice de Desenvolvimento da Educação Básica (IDEB) também abrange o Ensino Médio, e foram utilizadas as bases de dados específicas divulgadas pelo IDEB para essa etapa de ensino. Os dados foram processados para determinar a posição do IDEB por rede de ensino, ano e município. Em seguida, foram calculadas as variações de posição do IDEB em relação aos anos anteriores. O resultado é apresentado no dataframe df_posicao_ideb, contendo as informações relevantes para análise e comparação do IDEB no Ensino Médio.

In [ ]:
# Importação e leitura dos dados do IDEB - Ensino Médio
ideb_ensino_medio = pd.read_csv(r'I:\Freelas\Anuário de Dados - Goiás\Educação\bases limpas\IDEB - Ensino Médio.csv')

# Agrupamento dos dados por rede de ensino
grupo_rede = ideb_ensino_medio.groupby('Rede')
dataframes_separados = [grupo for _, grupo in grupo_rede]
dataframes_separados_por_rede_e_ano = []

# Separação dos dataframes por rede de ensino e ano
for df_rede in dataframes_separados:
    grupo_ano = df_rede.groupby('Ano')
    dataframes_separados_por_ano = [grupo for _, grupo in grupo_ano]
    dataframes_separados_por_rede_e_ano.extend(dataframes_separados_por_ano)

dataframes_com_posicao = []

# Cálculo da posição do IDEB por grupo (rede de ensino, ano)
for df_grupo in dataframes_separados_por_rede_e_ano:
    df_grupo['Posição IDEB'] = df_grupo['Nota IDEB'].rank(ascending=False, method='min')
    dataframes_com_posicao.append(df_grupo)

# Concatenação dos dataframes com a posição do IDEB
df_posicao_ideb = pd.concat(dataframes_com_posicao).reset_index(drop=True)

# Substituição de valores infinitos por NaN
df_posicao_ideb.replace([np.inf, -np.inf], np.nan, inplace=True)

# Conversão da coluna de posição do IDEB para tipo inteiro
df_posicao_ideb['Posição IDEB'] = df_posicao_ideb['Posição IDEB'].astype(float).fillna(0).astype(int)

# Cálculo da variação de posição do IDEB em relação aos anos anteriores
df_posicao_ideb['Delta Posição'] = df_posicao_ideb.groupby(['Rede', 'Município'])['Posição IDEB'].diff()

# Substituição de valores infinitos por NaN na coluna de variação de posição
df_posicao_ideb.replace([np.inf, -np.inf], np.nan, inplace=True)

# Conversão da coluna de variação de posição para tipo inteiro
df_posicao_ideb['Delta Posição'] = df_posicao_ideb['Delta Posição'].astype(float).fillna(0).astype(int)

# Ajuste dos valores de variação de posição para valores absolutos
df_posicao_ideb['Delta Posição'] = df_posicao_ideb['Delta Posição'].apply(lambda x: -x if x > 0 else abs(x))

# Exibição do dataframe com as posições e variações de posição do IDEB no Ensino Médio
df_posicao_ideb

,Ensino,Ano,UF,Município,Rede,Nota IDEB,Posição IDEB,Delta Posição
0,Ensino Médio Regular,2017,RO,Alta Floresta D'Oeste,Estadual,"3,9",1522,0
1,Ensino Médio Regular,2017,RO,Ariquemes,Estadual,"3,8",1814,0
2,Ensino Médio Regular,2017,RO,Cabixi,Estadual,"3,7",2100,0
3,Ensino Médio Regular,2017,RO,Cacoal,Estadual,"3,7",2100,0
4,Ensino Médio Regular,2017,RO,Cerejeiras,Estadual,"3,8",1814,0
...,...,...,...,...,...,...,...,...
34924,Ensino Médio Regular,2021,GO,Vianópolis,Pública,"4,5",926,-884
34925,Ensino Médio Regular,2021,GO,Vicentinópolis,Pública,"4,6",698,-550
34926,Ensino Médio Regular,2021,GO,Vila Boa,Pública,4,2144,-176
34927,Ensino Médio Regular,2021,GO,Vila Propício,Pública,"4,6",698,703
34928,Ensino Médio Regular,2021,DF,Brasília,Pública,4,2144,348

Foram aplicadas transformações nos dados, incluindo o cálculo da posição do IDEB por rede de ensino, município e ano. Em seguida, os resultados foram filtrados separadamente para o município de Goiânia e para o estado de Goiás, excluindo Goiânia. Os dados resultantes foram exportados para arquivos CSV e apresentados os primeiros registros de cada conjunto de dados filtrado.

In [ ]:
# Goiânia

# Filtrar dados do IDEB - Ensino Médio para Goiânia
df_posicao_ideb_goiania = df_posicao_ideb[df_posicao_ideb['Município'] == 'Goiânia']
df_posicao_ideb_goiania.to_csv(r'I:\Freelas\Anuário de Dados - Goiás\Educação\IDEB - Ensino Médio - Goiânia.csv', index=False)
df_posicao_ideb_goiania.head(2)

,Ensino,Ano,UF,Município,Rede,Nota IDEB,Posição IDEB,Delta Posição
5390,Ensino Médio Regular,2017,GO,Goiânia,Estadual,"4,5",301,0
10933,Ensino Médio Regular,2019,GO,Goiânia,Estadual,"4,6",807,-506

In [ ]:
# Goiás
# Filtrar dados do IDEB - Ensino Médio para Goiás (exceto Goiânia)
df_posicao_ideb_goias = df_posicao_ideb[df_posicao_ideb['UF'] == 'GO']
df_posicao_ideb_goias = df_posicao_ideb_goias[df_posicao_ideb_goias['Município'] != 'Goiânia']
df_posicao_ideb_goias = df_posicao_ideb_goias.sort_values(by=['Município', 'Rede', 'Ano'], ascending=True)
df_posicao_ideb_goias.to_csv(r'I:\Freelas\Anuário de Dados - Goiás\Educação\Goiás - IDEB - Ensino Médio.csv', index=False)
df_posicao_ideb_goias.head(2)

,Ensino,Ano,UF,Município,Rede,Nota IDEB,Posição IDEB,Delta Posição
5296,Ensino Médio Regular,2017,GO,Abadia de Goiás,Estadual,4,1243,0
10839,Ensino Médio Regular,2019,GO,Abadia de Goiás,Estadual,"4,6",807,436